// ============================================================
// Core Types for Lead Finder
// ============================================================

/** User-submitted search request */
export interface SearchRequest {
  query: string;
  targetType?: string;       // e.g. "pastor", "author", "investor"
  region?: string;           // e.g. "US", "UK"
  maxPeople?: number;        // max people to return
  sourcePreferences?: string[]; // e.g. ["official sites", "church pages", "wikipedia"]
  outputFormat?: "cards" | "table" | "csv";
  strictMode?: boolean;      // reject weak matches
}

/** A single search intent generated by the LLM */
export interface SearchIntent {
  personName: string;
  queryString: string;
  intentType: string; // e.g. "official_website", "wikipedia", "contact", "booking"
}

/** Raw result from OSV Web Search API */
export interface OSVSearchResult {
  url: string;
  title: string;
  content: string;
  engine: string;
  engines: string[];
  positions: number[];
  score: number;
  category: string;
}

export interface OSVSearchResponse {
  query: string;
  number_of_results: number;
  results: OSVSearchResult[];
  answers: string[];
  corrections: string[];
  infoboxes: any[];
  suggestions: string[];
  unresponsive_engines: string[];
}

/** Extracted page data from crawling */
export interface CrawledPage {
  url: string;
  title?: string;
  contents?: string;
  links?: string[];
  statusCode?: number;
  error?: string;
}

/** LLM classification of a single result */
export interface ClassifiedResult {
  url: string;
  title: string;
  snippet: string;
  personName: string;
  isAboutPerson: boolean;
  sourceType: "official" | "profile" | "contact" | "booking" | "interview" | "secondary" | "irrelevant";
  hasContactInfo: boolean;
  hasStaffInfo: boolean;
  hasBookingInfo: boolean;
  hasSocialLinks: boolean;
  outreachValue: "high" | "medium" | "low" | "none";
  evidence: string;
}

/** Final scored result for a person */
export interface PersonResult {
  name: string;
  role: string;
  organization: string;
  official_site: string;
  profile_links: string[];
  contact_links: string[];
  emails: string[];           // email addresses extracted from crawled pages
  inferred_email?: string;    // e.g. info@domain.com — common pattern, not verified
  evidence: string[];
  confidence: number;
  next_best_action: string;
  all_links: RankedLink[];
}

export interface RankedLink {
  url: string;
  title: string;
  sourceType: string;
  outreachValue: string;
  reason: string;
}

/** Full response returned to the client */
export interface DiscoverResponse {
  query: string;
  results: PersonResult[];
  metadata: {
    totalSearches: number;
    totalCrawled: number;
    totalClassified: number;
    processingTimeMs: number;
  };
}

/** Pipeline status updates sent via SSE */
export interface PipelineStatus {
  stage: "expanding" | "searching" | "crawling" | "classifying" | "ranking" | "done" | "error";
  message: string;
  progress?: number;
}
